title: Scott Einsidler's Website
description: Blog posts and Projects relating to things I'm working on and interested in!
author: Scott Einsidler
github: https://github.com/seinsidler
about: I love mathematics and programming, and the cross-section between the two. 
disqus_shortname: scotteinsidlerwebsite
google_analytics: UA-XXXXXXXX-Y
encoding: utf-8
enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-github
      link: "https://github.com/seinsidler"

# share:
#   twitter_username: github.io
#   fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://yellow-sun-1021.on.fleek.co/"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
